# Generated by Django 3.1.7 on 2021-05-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_animalusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalusers',
            options={},
        ),
    ]
